# Generated by Django 3.2.8 on 2021-12-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p18website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ID',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='JSProgram',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='package',
            name='content',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
