# Generated by Django 3.2.8 on 2021-12-07 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p18website', '0005_auto_20211207_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='JSProgram',
        ),
        migrations.RemoveField(
            model_name='package',
            name='content',
        ),
    ]
