#! /usr/bin/bash
# in file `run`

if [ "$1" == "install" ]; then
    python3 -m venv .
    source ./bin/activate
    pip3 install --upgrade pip
    pip install pytest
    pip install PyGithub
    pip install requests
    pip install datetime
    pip install GitPython
    pip install coverage
    pip install nose
fi

source ./bin/activate

python3 run.py "$1"

deactivate